x = input('Digite algo: ')
print('O tipo primitivo desse valor é: {}'.format(x.__class__))
print('Só tem espaços? {}'.format(x.isspace()))
print('É um número? {}'.format(x.isalnum()))
print('É alfabetico? {}'.format(x.isalpha()))
print('É alfanumerico? {}'.format(x.isalnum()))
print('Está em maiusculas? {}'.format(x.isupper()))
print('Está em minusculas? '.format(x.islower()))
print('Está captalizado? {}'.format(x.istitle()))